# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - wtp1-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      -   name: Publish
          shell: pwsh
          run: |
                dotnet publish world-tourist-passport-mvp-v2/src/PassportFunctions/PassportFunctions.csproj `
                -c Release `
                -o published
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
         app-name: 'wtp1-api'
         slot-name: 'Production'
         package: 'published'
